# Generated by Django 4.0.3 on 2022-04-21 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_command_confirmed_commandtypetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='pdf_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='commands/%y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='person_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='command',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
